# Generated by Django 4.1.3 on 2022-12-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourRestarant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinentalFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodTypes', models.CharField(max_length=50)),
                ('FoodTitle', models.CharField(max_length=100)),
                ('FoodSubTitle', models.CharField(max_length=120)),
                ('FoodPrice', models.IntegerField()),
                ('FoodDesc', models.CharField(max_length=150)),
                ('FoodImage', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='DumplingsFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodTypes', models.CharField(max_length=50)),
                ('FoodTitle', models.CharField(max_length=100)),
                ('FoodSubTitle', models.CharField(max_length=120)),
                ('FoodPrice', models.IntegerField()),
                ('FoodDesc', models.CharField(max_length=150)),
                ('FoodImage', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='IndianFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodTypes', models.CharField(max_length=50)),
                ('FoodTitle', models.CharField(max_length=100)),
                ('FoodSubTitle', models.CharField(max_length=120)),
                ('FoodPrice', models.IntegerField()),
                ('FoodDesc', models.CharField(max_length=150)),
                ('FoodImage', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
