# Generated by Django 4.1.3 on 2022-12-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourRestarant', '0002_continentalfood_dumplingsfood_indianfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continentalfood',
            name='FoodImage',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='dumplingsfood',
            name='FoodImage',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='indianfood',
            name='FoodImage',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='thaifood',
            name='FoodImage',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
