# Generated by Django 4.1.3 on 2023-01-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourRestarant', '0004_book_a_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('messagesss', models.CharField(max_length=300)),
            ],
        ),
    ]
